package com.gps.statistics.entity;

/**
 * Relation generated by MyEclipse Persistence Tools
 */

public class Relation implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String rid;

	private String deviceid;

	private String vehicleid;

	private String sim;

	private String account;

	private String type;

	private String typename;

	private String ownername;

	private String ownerphone;

	private String carstate;

	private String createtime;
	
	private String tablename;
	private String isnoice;
	
	private String storageCreator;//测试人
	private String storageTime;// 测试时间
	private String storageRemark;//备注
	// Constructors
 
	private String buyname;//购买人
	private String buytime;//购买时间
	private String payway;//付款方式
	private String prepay;//预付款
	private String paymonth;//月供
	private String payterm;//还款年限
	private String paywarndate;//预警时间
	
	private String receivetime;//接受时间
	private String worktime;//工作时间

	// Constructors

	/** default constructor */
	public Relation() {
	}

	/** full constructor */
	public Relation(String rid, String deviceid, String vehicleid, String sim,
			String account, String type, String typename, String ownername,
			String ownerphone, String carstate, String createtime, String tablename) {
		this.rid = rid;
		this.deviceid = deviceid;
		this.vehicleid = vehicleid;
		this.sim = sim;
		this.account = account;
		this.type = type;
		this.typename = typename;
		this.ownername = ownername;
		this.ownerphone = ownerphone;
		this.carstate = carstate;
		this.createtime = createtime;
		this.tablename = tablename;
	}

	// Property accessors

	public String getRid() {
		return this.rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	public String getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(String vehicleid) {
		this.vehicleid = vehicleid;
	}

	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public String getOwnername() {
		return this.ownername;
	}

	public void setOwnername(String ownername) {
		this.ownername = ownername;
	}

	public String getOwnerphone() {
		return this.ownerphone;
	}

	public void setOwnerphone(String ownerphone) {
		this.ownerphone = ownerphone;
	}

	public String getCarstate() {
		return this.carstate;
	}

	public void setCarstate(String carstate) {
		this.carstate = carstate;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getTablename() {
		return tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	public String getIsnoice() {
		return isnoice;
	}

	public void setIsnoice(String isnoice) {
		this.isnoice = isnoice;
	}

	public String getStorageCreator() {
		return storageCreator;
	}

	public void setStorageCreator(String storageCreator) {
		this.storageCreator = storageCreator;
	}

	public String getStorageTime() {
		return storageTime;
	}

	public void setStorageTime(String storageTime) {
		this.storageTime = storageTime;
	}

	public String getStorageRemark() {
		return storageRemark;
	}

	public void setStorageRemark(String storageRemark) {
		this.storageRemark = storageRemark;
	}

	public String getBuyname() {
		return buyname;
	}

	public void setBuyname(String buyname) {
		this.buyname = buyname;
	}

	public String getBuytime() {
		return buytime;
	}

	public void setBuytime(String buytime) {
		this.buytime = buytime;
	}

	public String getPayway() {
		return payway;
	}

	public void setPayway(String payway) {
		this.payway = payway;
	}

	public String getPrepay() {
		return prepay;
	}

	public void setPrepay(String prepay) {
		this.prepay = prepay;
	}

	public String getPaymonth() {
		return paymonth;
	}

	public void setPaymonth(String paymonth) {
		this.paymonth = paymonth;
	}

	public String getPayterm() {
		return payterm;
	}

	public void setPayterm(String payterm) {
		this.payterm = payterm;
	}

	public String getPaywarndate() {
		return paywarndate;
	}

	public void setPaywarndate(String paywarndate) {
		this.paywarndate = paywarndate;
	}

	public String getReceivetime() {
		return receivetime;
	}

	public void setReceivetime(String receivetime) {
		this.receivetime = receivetime;
	}

	public String getWorktime() {
		return worktime;
	}

	public void setWorktime(String worktime) {
		this.worktime = worktime;
	}

}