package com.gps.vehiclemng.entity;

import java.util.Date;

/**
 * Commandorigin generated by MyEclipse Persistence Tools
 */

public class Commandorigin implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String coid;

	private String device;

	private String sim;

	private String command;

	private String descrip;

	private Date sendtime;

	private String state;

	private String username;

	// Constructors

	/** default constructor */
	public Commandorigin() {
	}

	/** full constructor */
	public Commandorigin(String coid, String device, String sim, String command,
			String comment, Date sendtime, String state, String user) {
		this.coid = coid;
		this.device = device;
		this.sim = sim;
		this.command = command;
		this.descrip = comment;
		this.sendtime = sendtime;
		this.state = state;
		this.username = user;
	}

	// Property accessors

	public String getCoid() {
		return this.coid;
	}

	public void setCoid(String coid) {
		this.coid = coid;
	}

	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	public String getCommand() {
		return this.command;
	}

	public void setCommand(String command) {
		this.command = command;
	}

	 

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDescrip() {
		return descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	 

}