package com.gps.vehiclemng.entity;

/**
 * Relation generated by MyEclipse Persistence Tools
 */

public class Car implements java.io.Serializable {

	// Fields

	/**
	 *  车辆表
	 */
	private static final long serialVersionUID = 1L;

	private String rid;

	private String deviceid;//设备id

	private String vehicleid;//车辆id
	private String carkey;//车钥匙状态
	private String sim;//手机号码
	private String longitude;//纬度
	private String latitude;//经度
	private String account;//账号
	private String cname;//用户名
	private String type;//机械种类

	private String typename;//机械型号

	private String ownername;//所有者

	private String ownerphone;//所有者电话

	private String carstate;//车辆销售状态
	private String carstatename;//车辆状态名称

	private String createtime;
	private String tablename;
	private String isnoice;
	private Integer start ;
	private Integer end  ;
	private Integer curentPage =1;
	private Integer pageSize=10;
	
	private String storageCreator;//测试人
	private String storageTime;// 测试时间
	private String storageRemark;//备注
	// Constructors
 
	private String buyname;//购买人
	private String buytime;//购买时间
	private String payway;//付款方式
	private String prepay;//预付款
	private String paymonth;//月供
	private String payterm;//还款年限
	private String paywarndate;//预警时间
	private String receivetime;//接受时间
	private String worktime;//工作时间
	private String locate;//地理位置
	
	
	private String vehicleidstate ; //机械报警
	private String deviceidstate ; //终端报警
	private String vehicleidlockstate ;//被锁定
	private String gpsstate ;//定位异常 10天未定位
	private String nowork ;//长时间不工作 10天未工作
	
	private String flg ;//长时间不工作 10天未工作
	 

	public String getNowork() {
		return nowork;
	}

	public void setNowork(String nowork) {
		this.nowork = nowork;
	}

	public String getVehicleidstate() {
		return vehicleidstate;
	}

	public void setVehicleidstate(String vehicleidstate) {
		this.vehicleidstate = vehicleidstate;
	}

	public String getDeviceidstate() {
		return deviceidstate;
	}

	public void setDeviceidstate(String deviceidstate) {
		this.deviceidstate = deviceidstate;
	}

	public String getVehicleidlockstate() {
		return vehicleidlockstate;
	}

	public void setVehicleidlockstate(String vehicleidlockstate) {
		this.vehicleidlockstate = vehicleidlockstate;
	}

	public String getGpsstate() {
		return gpsstate;
	}

	public void setGpsstate(String gpsstate) {
		this.gpsstate = gpsstate;
	}

	public String getLocate() {
		return locate;
	}

	public void setLocate(String locate) {
		this.locate = locate;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	public Integer getCurentPage() {
		return curentPage;
	}

	public void setCurentPage(Integer curentPage) {
		this.curentPage = curentPage;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public String getTablename() {
		return tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	/** default constructor */
	public Car() {
	}

	/** full constructor */
	public Car(String deviceid, String vehicleid, String sim,
			String account, String type, String typename, String ownername,
			String ownerphone, String carstate, String createtime) {
		this.deviceid = deviceid;
		this.vehicleid = vehicleid;
		this.sim = sim;
		this.account = account;
		this.type = type;
		this.typename = typename;
		this.ownername = ownername;
		this.ownerphone = ownerphone;
		this.carstate = carstate;
		this.createtime = createtime;
	}

	// Property accessors

	public String getRid() {
		return this.rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	public String getVehicleid() {
		return this.vehicleid;
	}

	public void setVehicleid(String vehicleid) {
		this.vehicleid = vehicleid;
	}

	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public String getOwnername() {
		return this.ownername;
	}

	public void setOwnername(String ownername) {
		this.ownername = ownername;
	}

	public String getOwnerphone() {
		return this.ownerphone;
	}

	public void setOwnerphone(String ownerphone) {
		this.ownerphone = ownerphone;
	}

	public String getCarstate() {
		return this.carstate;
	}

	public void setCarstate(String carstate) {
		this.carstate = carstate;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getIsnoice() {
		return isnoice;
	}

	public void setIsnoice(String isnoice) {
		this.isnoice = isnoice;
	}

	public String getCarstatename() {
		return carstatename;
	}

	public void setCarstatename(String carstatename) {
		this.carstatename = carstatename;
	}

	public String getStorageCreator() {
		return storageCreator;
	}

	public void setStorageCreator(String storageCreator) {
		this.storageCreator = storageCreator;
	}

	public String getStorageTime() {
		return storageTime;
	}

	public void setStorageTime(String storageTime) {
		this.storageTime = storageTime;
	}

	public String getStorageRemark() {
		return storageRemark;
	}

	public void setStorageRemark(String storageRemark) {
		this.storageRemark = storageRemark;
	}

	public String getBuyname() {
		return buyname;
	}

	public void setBuyname(String buyname) {
		this.buyname = buyname;
	}

	public String getBuytime() {
		return buytime;
	}

	public void setBuytime(String buytime) {
		this.buytime = buytime;
	}

	public String getPayway() {
		return payway;
	}

	public void setPayway(String payway) {
		this.payway = payway;
	}

	public String getPrepay() {
		return prepay;
	}

	public void setPrepay(String prepay) {
		this.prepay = prepay;
	}

	public String getPaymonth() {
		return paymonth;
	}

	public void setPaymonth(String paymonth) {
		this.paymonth = paymonth;
	}

	public String getPayterm() {
		return payterm;
	}

	public void setPayterm(String payterm) {
		this.payterm = payterm;
	}

	public String getPaywarndate() {
		return paywarndate;
	}

	public void setPaywarndate(String paywarndate) {
		this.paywarndate = paywarndate;
	}

	public String getReceivetime() {
		return receivetime;
	}

	public void setReceivetime(String receivetime) {
		this.receivetime = receivetime;
	}

	public String getWorktime() {
		return worktime;
	}

	public void setWorktime(String worktime) {
		this.worktime = worktime;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getCarkey() {
		return carkey;
	}

	public void setCarkey(String carkey) {
		this.carkey = carkey;
	}

	public String getFlg() {
		return flg;
	}

	public void setFlg(String flg) {
		this.flg = flg;
	}

}