package com.gps.vehiclemng.entity;

import java.util.Date;

/**
 * Messageorigin generated by MyEclipse Persistence Tools
 */

public class Messageorigin implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String moid;

	private String sim;

	private String message;

	private Date receivetime;
	
	private String deviceid;

	// Constructors

	/** default constructor */
	public Messageorigin() {
	}

	/** full constructor */
	public Messageorigin(String moid, String sim, String message, Date receivetime) {
		this.moid = moid;
		this.sim = sim;
		this.message = message;
		this.receivetime = receivetime;
	}

	// Property accessors

	public String getMoid() {
		return this.moid;
	}

	public void setMoid(String moid) {
		this.moid = moid;
	}

	public String getSim() {
		return this.sim;
	}

	public void setSim(String sim) {
		this.sim = sim;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Date getReceivetime() {
		return this.receivetime;
	}

	public void setReceivetime(Date receivetime) {
		this.receivetime = receivetime;
	}

	public String getDeviceid() {
		return deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

}