package com.gps.statistics.entity;

import java.util.Date;

/**
 * Messagereport generated by MyEclipse Persistence Tools
 */

public class Messagereport implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String mrid;

	private String deviceid;//设置ID

	private String infotype;//信息类型

	private Date receivetime;//信息发送时间

	private String rbrq;//日报日期

	private String kjcs;//开机次数

	private String yh;//油耗

	private String cyskqsj;//车钥匙开启时间

	private String dsyzsj;//怠速运转时间

	private String gsyzsj;//高速运转时间

	private String zzkjsj;//最早开机时间

	private String zwkjsj;//最晚关机时间

	// Constructors

	/** default constructor */
	public Messagereport() {
	}

	/** full constructor */
	public Messagereport(String deviceid, String infotype, Date receivetime,
			String rbrq, String kjcs, String yh, String cyskqsj, String dsyzsj,
			String gsyzsj, String zzkjsj, String zwkjsj) {
		this.deviceid = deviceid;
		this.infotype = infotype;
		this.receivetime = receivetime;
		this.rbrq = rbrq;
		this.kjcs = kjcs;
		this.yh = yh;
		this.cyskqsj = cyskqsj;
		this.dsyzsj = dsyzsj;
		this.gsyzsj = gsyzsj;
		this.zzkjsj = zzkjsj;
		this.zwkjsj = zwkjsj;
	}

	// Property accessors

	public String getMrid() {
		return this.mrid;
	}

	public void setMrid(String mrid) {
		this.mrid = mrid;
	}

	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	public String getInfotype() {
		return this.infotype;
	}

	public void setInfotype(String infotype) {
		this.infotype = infotype;
	}

	public Date getReceivetime() {
		return this.receivetime;
	}

	public void setReceivetime(Date receivetime) {
		this.receivetime = receivetime;
	}

	public String getRbrq() {
		return this.rbrq;
	}

	public void setRbrq(String rbrq) {
		this.rbrq = rbrq;
	}

	public String getKjcs() {
		return this.kjcs;
	}

	public void setKjcs(String kjcs) {
		this.kjcs = kjcs;
	}

	public String getYh() {
		return this.yh;
	}

	public void setYh(String yh) {
		this.yh = yh;
	}

	public String getCyskqsj() {
		return this.cyskqsj;
	}

	public void setCyskqsj(String cyskqsj) {
		this.cyskqsj = cyskqsj;
	}

	public String getDsyzsj() {
		return this.dsyzsj;
	}

	public void setDsyzsj(String dsyzsj) {
		this.dsyzsj = dsyzsj;
	}

	public String getGsyzsj() {
		return this.gsyzsj;
	}

	public void setGsyzsj(String gsyzsj) {
		this.gsyzsj = gsyzsj;
	}

	public String getZzkjsj() {
		return this.zzkjsj;
	}

	public void setZzkjsj(String zzkjsj) {
		this.zzkjsj = zzkjsj;
	}

	public String getZwkjsj() {
		return this.zwkjsj;
	}

	public void setZwkjsj(String zwkjsj) {
		this.zwkjsj = zwkjsj;
	}

}