package com.gps.login.entity;

/**
 * Account generated by MyEclipse Persistence Tools
 */

public class Account implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String aid;

	private String name;
	private String cname;

	private String pass;

	private String parentname;

	private Integer maxchild;

	private Integer maxlevel;
	private Integer carnums;
	private Integer start ;
	private Integer end  ;
	private Integer curentPage =1;
	private Integer pageSize=10;
	// Constructors

	public Integer getCurentPage() {
		return curentPage;
	}

	public void setCurentPage(Integer curentPage) {
		this.curentPage = curentPage;
	}

	public Integer getPageSize() {
		return pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	public Integer getStart() {
		return start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	public Integer getEnd() {
		return end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	/** default constructor */
	public Account() {
	}

	public Account(String aid, String name, String pass, String parentname,
			Integer maxchild, Integer maxlevel) {
		super();
		this.aid = aid;
		this.name = name;
		this.pass = pass;
		this.parentname = parentname;
		this.maxchild = maxchild;
		this.maxlevel = maxlevel;
	}

	public String getAid() {
		return aid;
	}

	public void setAid(String aid) {
		this.aid = aid;
	}

	public Integer getMaxchild() {
		return maxchild;
	}

	public void setMaxchild(Integer maxchild) {
		this.maxchild = maxchild;
	}

	public Integer getMaxlevel() {
		return maxlevel;
	}

	public void setMaxlevel(Integer maxlevel) {
		this.maxlevel = maxlevel;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public String getPass() {
		return pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Integer getCarnums() {
		return carnums;
	}

	public void setCarnums(Integer carnums) {
		this.carnums = carnums;
	}

}