package com.gps.login.entity;

import java.util.Date;

/**
 * Loginlog generated by MyEclipse Persistence Tools
 */

public class Loginlog implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String llid;

	private String account;

	private String ip;

	private Date time;

	// Constructors

	/** default constructor */
	public Loginlog() {
	}

	/** full constructor */
	public Loginlog(String account, String ip, Date time) {
		this.account = account;
		this.ip = ip;
		this.time = time;
	}

	// Property accessors

	public String getLlid() {
		return this.llid;
	}

	public void setLlid(String llid) {
		this.llid = llid;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}